list: $/diveramkt/flexgallery/models/bannerpages/columns.yaml
modelClass: Diveramkt\Flexgallery\Models\BannerPages
title: BannersPages
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'diveramkt/flexgallery/bannerspages/update/:id'
