list: $/diveramkt/flexgallery/models/banner/columns.yaml
modelClass: Diveramkt\Flexgallery\Models\Banner
title: Banners
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'diveramkt/flexgallery/banners/update/:id'
