onebanner:
    label: Banners
    manage:
        form: $/diveramkt/flexgallery/models/onebanner/relation_fields.yaml
        list: $/diveramkt/flexgallery/models/onebanner/relation_columns.yaml
    view:
        list: $/diveramkt/flexgallery/models/onebanner/relation_columns.yaml
        toolbarButtons: create|delete|sort