plugin:
    name: 'diveramkt.flexgallery::lang.plugin.name'
    description: 'diveramkt.flexgallery::lang.plugin.description'
    author: DiveraMkt
    icon: oc-icon-image
    homepage: 'http://www.diveramkt.com.br'
permissions:
    manage_banners:
        tab: 'diveramkt.flexgallery::lang.plugin.name'
        label: 'diveramkt.flexgallery::lang.flexgallery.banner'
    manage_banners_pages:
        tab: 'diveramkt.flexgallery::lang.plugin.name'
        label: 'diveramkt.flexgallery::lang.flexgallery.banners_page'
navigation:
    main-menu-flexgallery:
        label: 'diveramkt.flexgallery::lang.plugin.name'
        url: diveramkt/flexgallery/banners
        icon: icon-image
        permissions:
            - manage_banners
        sideMenu:
            side-menu-banners:
                label: 'diveramkt.flexgallery::lang.flexgallery.banners'
                url: diveramkt/flexgallery/banners
                icon: icon-desktop
                permissions:
                    - manage_banners
            side-menu-banners_page:
                label: 'diveramkt.flexgallery::lang.flexgallery.banners_page'
                url: diveramkt/flexgallery/bannerspages
                icon: icon-image
