list: $/diveramkt/flexgallery/models/onebanner/columns.yaml
modelClass: Diveramkt\Flexgallery\Models\OneBanner
title: OneBanner
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
defaultSort:
    column: sort_order
    direction: asc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'diveramkt/flexgallery/onebanner/update/:id'
